import { type CSSProperties } from 'react';
import { themeCssVariables } from 'twenty-sdk/ui';

export const getBaitkPanelStyles = (): Record<string, CSSProperties> => ({
  container: {
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.sm,
    color: themeCssVariables.font.color.primary,
    background: themeCssVariables.background.primary,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    boxSizing: 'border-box',
  },
  header: {
    padding: themeCssVariables.spacing[4],
    borderBottom: `1px solid ${themeCssVariables.border.color.light}`,
    flexShrink: 0,
  },
  pageTitle: {
    fontSize: themeCssVariables.font.size.md,
    fontWeight: themeCssVariables.font.weight.semiBold,
    color: themeCssVariables.font.color.primary,
    margin: 0,
  },
  pageSubtitle: {
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.regular,
    color: themeCssVariables.font.color.tertiary,
    margin: 0,
    marginTop: themeCssVariables.spacing[2],
    lineHeight: 1.5,
  },
  body: {
    flex: 1,
    minHeight: 0,
    padding: themeCssVariables.spacing[4],
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[6],
    overflowY: 'auto',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[3],
  },
  sectionTitle: {
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.semiBold,
    color: themeCssVariables.font.color.primary,
    margin: 0,
  },
  sectionDescription: {
    fontSize: themeCssVariables.font.size.sm,
    color: themeCssVariables.font.color.tertiary,
    margin: 0,
    lineHeight: 1.5,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: themeCssVariables.spacing[3],
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[1],
  },
  label: {
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    color: themeCssVariables.font.color.secondary,
  },
  input: {
    backgroundColor: themeCssVariables.background.transparent.lighter,
    border: `1px solid ${themeCssVariables.border.color.medium}`,
    borderRadius: themeCssVariables.border.radius.sm,
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    display: 'flex',
    flexGrow: 1,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.md,
    fontWeight: themeCssVariables.font.weight.regular,
    height: themeCssVariables.spacing[8],
    maxWidth: 'none',
    outline: 'none',
    padding: themeCssVariables.spacing[2],
    textOverflow: 'ellipsis',
    width: '100%',
  },
  select: {
    appearance: 'none',
    WebkitAppearance: 'none',
    background: 'var(--t-background-transparent-lighter)',
    border: '1px solid var(--t-border-color-medium)',
    borderRadius: 'var(--t-border-radius-sm)',
    padding: 'var(--t-spacing-2) var(--t-spacing-3)',
    color: 'var(--t-font-color-primary)',
    fontSize: 'var(--t-font-size-md)',
    fontFamily: 'var(--t-font-family)',
    height: themeCssVariables.spacing[8],
    cursor: 'pointer',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  actionsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[2],
    alignItems: 'center',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  tableHeadCell: {
    padding: `${themeCssVariables.spacing[2]} ${themeCssVariables.spacing[3]}`,
    textAlign: 'left',
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    color: themeCssVariables.font.color.tertiary,
    borderBottom: `1px solid ${themeCssVariables.border.color.light}`,
  },
  tableCell: {
    padding: `${themeCssVariables.spacing[2]} ${themeCssVariables.spacing[3]}`,
    fontSize: themeCssVariables.font.size.sm,
    color: themeCssVariables.font.color.primary,
    borderBottom: `1px solid ${themeCssVariables.border.color.light}`,
    verticalAlign: 'middle',
  },
  tableCellSecondary: {
    padding: `${themeCssVariables.spacing[2]} ${themeCssVariables.spacing[3]}`,
    fontSize: themeCssVariables.font.size.sm,
    color: themeCssVariables.font.color.secondary,
    borderBottom: `1px solid ${themeCssVariables.border.color.light}`,
    verticalAlign: 'middle',
  },
  tableActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[2],
  },
  centeredState: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: themeCssVariables.spacing[4],
    height: '100%',
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.sm,
  },
});
